<?php
/**
 * Created by PhpStorm.
 * User: H
 * Date: 2017/9/15
 * Time: 13:39
 */
namespace app\models;

use yii\db\ActiveRecord;

class User extends ActiveRecord{
    public static function tableName()
    {
        return 'user';
    }

    public function attributeLabels()
    {
        return [
            'uname' =>  '用户姓名',
            'uage'  =>  '用户年龄',
            'usex'  =>  '用户性别',
        ];
    }

    public function rules()
    {
        return [
            [['uname', 'uage', 'usex'], 'required', 'message' => '{attribute}不能为空！'],
            [['uname', 'uage'], 'trim'],
            ['uname', 'string', 'length' => [2, 20], 'tooShort'=>'{attribute}长度2-20'],
        ];
    }

    public function behaviors()
    {
        return parent::behaviors(); // TODO: Change the autogenerated stub
    }
}